// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHRvYl2AseW1cVVoM-JaCyKKR7VVzOSnY',
    appId: '1:25787072424:web:f416d15a509302b314679d',
    messagingSenderId: '25787072424',
    projectId: 'ihrd-mobile',
    authDomain: 'ihrd-mobile.firebaseapp.com',
    storageBucket: 'ihrd-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcE-pfxA_6e1G8hP1_tgomICbUnRTLQB4',
    appId: '1:25787072424:android:cf8a23ea0ad849bc14679d',
    messagingSenderId: '25787072424',
    projectId: 'ihrd-mobile',
    storageBucket: 'ihrd-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfkFUGr60cgLXXzlO1R1o68nQQb6LwdCg',
    appId: '1:25787072424:ios:e1e77a86431bc06814679d',
    messagingSenderId: '25787072424',
    projectId: 'ihrd-mobile',
    storageBucket: 'ihrd-mobile.appspot.com',
    androidClientId:
        '25787072424-f1cvlanl2kp7h9p89giit60kega302l8.apps.googleusercontent.com',
    iosClientId:
        '25787072424-cck3ntcijiegk527uk96p1ppuifuopiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ihrdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfkFUGr60cgLXXzlO1R1o68nQQb6LwdCg',
    appId: '1:25787072424:ios:e1e77a86431bc06814679d',
    messagingSenderId: '25787072424',
    projectId: 'ihrd-mobile',
    storageBucket: 'ihrd-mobile.appspot.com',
    androidClientId:
        '25787072424-f1cvlanl2kp7h9p89giit60kega302l8.apps.googleusercontent.com',
    iosClientId:
        '25787072424-cck3ntcijiegk527uk96p1ppuifuopiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ihrdApp',
  );
}
