import 'package:flutter_application_1/institutions/institution_class.dart';

List<Poly> polyList = const [
  Poly(
    name: 'E K Nayanar Memorial Model Polytechnic College Kallyassery',
    address: 'Kallyassery P.O., Kannur District. Pin – 670562',
    about:
        'E K Nayanar Memorial Model Polytechnic College Kallyassery is established in 1997, offers 3 year regular diploma courses in Computer Hardware Engineering, Bio-Medical Engineering & Computer Engineering  affiliated to Board of  Technical Education, Kerala.',
    phone: '0497-2780287',
    mobile: '8547005082',
    email: 'eknmmptkallyassery@ihrd.ac.in',
    website: 'https://mptkallyassery.ihrd.ac.in/',
    principal: 'The Principal',
    nearestRailwayStation: 'Kannur',
    nearestBusStand: 'Kallyassery',
    courses: [
      'Computer Hardware Engineering (60 Seats)',
      'Bio-Medical Engineering (60 Seats)',
      'Computer Engineering (60 Seats)',
    ],
    ihrdCourses: [],
  ),
  Poly(
    name: 'Model Residential Polytechnic College Kuzhalmanam',
    address: 'Kannanur P O., Kuzhalmannam, Palakkad Dist., Pin- 678 702',
    about:
        'Model Residential Polytechnic College Kuzhalmanam is established in 2010, offers 3 year regular diploma courses in Civil Engineering affiliated to Board of Technical Education, Kerala.',
    phone: '04922 2729007',
    mobile: '8547005086',
    email: 'mrptckuzhalmannam@ihrd.ac.in',
    website: 'https://ihrd.ac.in/index.php/institutions/model-polytechnics/207-model-residential-polytechnic-college-kozhalmannam',
    principal: 'The Principal',
    nearestRailwayStation: 'Palakkad - 15 KM',
    nearestBusStand: 'Kuzhalmanam - 3 KM',
    courses: ['Civil Engineering'],
    ihrdCourses: [],
  ),
  Poly(
    name: 'Model Polytechnic College Painavu',
    address:
        'Kuyilimala, A R Camp road, Painavu PO, Idukki Dist., Pin - 685 603',
    about:
        'Model Polytechnic College Painavu offers 3 year diploma courses in Computer Hardware Engineering, Computer Engineering, Biomedical Engineering, and Electronics & Communication Engineering. It was established in 1997.',
    phone: '04862-2322460 /297617/944757615',
    mobile: '8547005084',
    email: 'mptpainavu.ihrd.ac.in',
    website: 'http://www.mptpainavu.ihrd.ac.in/',
    principal: 'Principal',
    nearestRailwayStation: 'Aluva- 110 KM',
    nearestBusStand: 'Kattappana - 35 KM',
    courses: [
      'Computer Hardware Engineering',
      'Computer Engineering',
      'Biomedical Engineering',
      'Electronics & Communication Engineering',
    ],
    ihrdCourses: ['PGDCA'],
  ),
  Poly(
    name: 'Model Polytechnic College Mattakkara',
    address: 'Mattakkara P.O, Kottayam Dist., Pin - 686 564',
    about:
        'Model Polytechnic College Mattakkara is affiliated to Board of Technical Education, Kerala and approved by Government of Kerala. It was established in 1984 with regular courses of Electronics Engineering, Computer Hardware Engineering, Electronics & Communication Engineering and Computer Engineering.',
    phone: '0481-2542022',
    mobile: '8547005081',
    email: 'mptmattakkara@ihrd.ac.in',
    website: 'https://mptmattakkara.ihrd.ac.in/',
    principal: 'The Principal',
    nearestRailwayStation: 'Kottayam - 23 Km',
    nearestBusStand: 'Ayarkunnam - 6 Km',
    courses: [
      'Electronics Engineering',
      'Computer Hardware Engineering',
      'Electronics & Communication Engineering',
      'Computer Engineering',
    ],
    ihrdCourses: [],
  ),
  Poly(
    name: 'Model Polytechnic College Karunagappally',
    address:
        'Maliyekkal Junction, Edakulangara P.O, Karunagappally, Kollam Dist., Pin – 690523',
    about:
        'Model Polytechnic College Karunagappally is established in 1997, offers 3 year regular diploma courses in Electronics Engineering, Computer Hardware Engineering, Electronics & Communication Engineering, Computer Engineering, Electrical & Electronics Engineering affiliated to Board of Technical Education, Kerala.',
    phone: '0476-2623597',
    mobile: '8547005083',
    email: 'mptkarunagappally@ihrd.ac.in',
    website: 'https://mptkarunagappally.ihrd.ac.in/',
    principal: 'The Principal',
    nearestRailwayStation: 'Karunagappally - 3 Km',
    nearestBusStand: 'Karunagappally - 2 Km',
    courses: [
      'Electronics Engineering',
      'Electronics & Communication Engineering',
      'Computer Hardware Engineering',
      'Computer Engineering',
      'Electrical & Electronics Engineering',
    ],
    ihrdCourses: ['PGDCA', 'DCA', 'DDTOA'],
  ),
  Poly(
    name: 'Model Polytechnic College Poonjar',
    address: 'Thekkekara P.O, Kottayam Dist., Pin - 686 582',
    about:
        'Model Polytechnic College Poonjar is established in 2007, offers 3 year regular diploma courses in Electronics Engineering, Computer Hardware Engineering, Electronics & Communication Engineering affiliated to Board of Technical Education, Kerala.',
    phone: '04822272266',
    mobile: '8547005085',
    email: 'mptpoonjar@ihrd.ac.in',
    website: 'https://mptpoonjar.ihrd.ac.in/',
    principal: 'The Principal',
    nearestRailwayStation: 'Kottayam - 23 Km',
    nearestBusStand: 'Erattupetta - 6 Km',
    courses: [
      'Electronics Engineering',
      'Computer Hardware Engineering',
    ],
    ihrdCourses: [],
  ),
  Poly(
    name: 'K.Karunakaran Memorial Model Polytechnic College Mala',
    address: 'Kallettumkara P.O., Mala, Thrissur District. Pin – 680 683',
    about:
        'K.Karunakaran Memorial Model Polytechnic College Mala is established in 1993, offers 3 year regular diploma courses in Electronics Engineering, Computer Hardware Engineering, Bio-Medical Engineering & Computer Engineering affiliated to Board of Technical Education, Kerala.',
    phone: '0480-2720746',
    mobile: '8547005080',
    email: 'mptmala@ihrd.ac.in',
    website: 'https://mptmala.ihrd.ac.in/',
    principal: 'The Principal',
    nearestRailwayStation: 'Irinjalakkuda',
    nearestBusStand: 'Kallettumkara',
    courses: [
      'Electronics Engineering',
      'Computer Hardware Engineering',
      'Bio-Medical Engineering',
      'Computer Engineering',
    ],
    ihrdCourses: ['DCA', 'PGDCA'],
  ),
  Poly(
    name: 'Model Polytechnic College Vadakara',
    address: 'Nut Street, Vadakara, Kozhikode Dist., Pin - 673 104',
    about:
        'The Model Polytechnic College,Vadakara is the brain child of intitute of Human Resources Development ( I H R D ) established by the Govt. of Kerala in the year 1988,whose main objective is to function as a catalyst to foster the growth of electronics ,computer and specialised feilds such as Medical Electronics throw a plethora of innovative endeavours. The Polytechnic College offers three year Diploma cource in applied electronics, Computer hardware maintanance and Medical Electronics,the courses being recognised by the PSC.The institution has been accredited by the National Board of Aaccreditation (NBA) of the All India Council for Technical Education (AICTE) New Delhi.',
    phone: '0496-2524920',
    mobile: '8547005079',
    email: 'mptvadakara@ihrd.ac.in',
    website: 'https://mptvadakara.ihrd.ac.in/',
    principal: 'The Principal',
    nearestRailwayStation: 'Vadakara - 1 KM',
    nearestBusStand: 'Vadakara - 1 KM',
    courses: [
      'Computer Hardware Engineering',
      'Biomedical Engineering',
      'Electrical & Electronics Engineering',
      'Electronics Engineering',
    ],
    ihrdCourses: ['PGDCA', 'DDT & PM'],
  ),
];
